apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: tech-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/postgres
