apiVersion: v1
kind: Service
metadata:
  name: tech-app
  namespace: tech-namespace
spec:
  selector:
    app: tech-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
